spring:
  application.name: later
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/later"
    username: ${LATER_USER}
    password: ${LATER_PASSWORD}
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
